### ISSUE TITLE
Error Uninstalling Component

### ISSUE THREAD

**Issue by K2Joom** [Niambie/jfoobar#10]
This may be specific to my previous issue, regarding numerics in the component name.
After trying to uninstall such a component an error is returned:

Failed deleting en-GB.com_ks.ini
Failed to delete language/en-GB/en-GB.com_ks.ini
Failed deleting en-GB.com_ks.sys.ini
Failed to delete language/en-GB/en-GB.com_ks.sys.ini
Failed deleting en-GB.com_ks.ini
Failed to delete administrator/language/en-GB/en-GB.com_ks.ini
Failed deleting en-GB.com_ks.sys.ini
Failed to delete administrator/language/en-GB/en-GB.com_ks.sys.ini

All other files are removed successfully.

Simon

**Comment by AmyStephen** [comment]
I think Cristina and I have this one fixed - can you give it a try and see (You'll have to redownload and install.)

Thanks!

**Comment by K2Joom** [comment]
Redownload and install!! you mean it does not do it automagically?

Thanks :)
