### ISSUE TITLE
getCmd vs getVar

### ISSUE THREAD

**Issue by ghazal** [Niambie/jfoobar#12]
Hi, again,
Note : I hope you won't mind getting a lot questions from my part, sometimes probably stupid, but I am really very interested by this extension and intend to use it.

That said:
is there a specific reason for using getVar instead of getCmd in mycomps.php (ie name of component : com_mycomp)
like :
$controller->execute(JRequest::getVar('task',''));

instead of :
$controller->execute(JRequest::getCmd('task'));

as seen in native components.

**Comment by mbabker** [comment]
All of the JRequest get functions are just proxies to getVar, just setting some values in the declaration on how to handle things.  Neither practice is technically incorrect, but with getVar, it appears you would need to set a couple other values in the declaration to handle filtering.

**Comment by AmyStephen** [comment]
Yes, use JRequest with the most appropriate method for filtering. 

Here's a good resource: http://docs.joomla.org/Secure_coding_guidelines

Thanks ghazal!
