### ISSUE TITLE
"Undefined property: stdClass::$text" in plugin loadmodule

### ISSUE THREAD

**Issue by ghazal** [Niambie/jfoobar#14]
Hi again, 
with php display errors on, I get :
Notice: Undefined property: stdClass::$text in ***/plugins/content/loadmodule/loadmodule.php on line 30 
 on a display of an item  (no error for a category)

Not a big deal, but I thought it was better to notify this issue.

**Comment by mbabker** [comment]
Thanks, fixed it up.  The content plugins look for a "text" item within the $article object, which in the front end com_content article view is either just the fulltext item or the introtext + fulltext items depending on settings.  Just needed to define a text item here.
