### ISSUE TITLE
Pb re display of all items in one category

### ISSUE THREAD

**Issue by ghazal** [Niambie/jfoobar#15]
Hi,
description :
- created a cat parent, 2 cats children, articles/items in each cats children
- when linking with a menu link (list) to one of the categories children, ALL articles/items (pertaining to cat child 1 and cat child 2) are displayed.
  That's not what's expected, I may say.

Last install (after std stuff corrected, thanks for this one)

**Comment by sunny000** [comment]
The changes below worked for me:

changes to:  com_cats/views/cats/tmpl/default.php

   JHtml::addIncludePath(JPATH_COMPONENT.'/helpers');
- $catId = JRequest::getVar('id');
  
  foreach ($this->items as $item) :
- if($item->catid != $catId) {continue;}

**Comment by ghazal** [comment]
Wow, thanks a lot. 
It works.
I wasn't looking at all in default.php, I was rather checking in "models" and then view.html.php.
Tks again.
