### ISSUE TITLE
PLG_SYSTEM_CREATE_INSTALL_SUCCESS

### ISSUE THREAD

**Issue by betweenbrain** [Niambie/jfoobar#17]
When creating a new extension, the success message displayed is "PLG_SYSTEM_CREATE_INSTALL_SUCCESS".

Although the proper language files are created, and do exist with the correct strings, is this string not being displayed as the new language file doesn't exist before administrator/component/com_jfoobar/media/create.php line 215 calls it?

Could the language files be created sooner or should a string from com_jfoobar be called instead?

**Comment by AmyStephen** [comment]
Gave you commit access, Matt. Will look into this but if you figure it out before me, feel free.

Welcome to the team! :)

Thanks!

**Comment by betweenbrain** [comment]
Thanks! I'll see what I can figure out.

Best,

Matt Thomas
Founder betweenbrain http://betweenbrain.com/™
Lead Developer Construct Template Development
Frameworkhttp://joomlaengineering.com/
Phone: 203.632.9322
Twitter: @betweenbrain
Github: https://github.com/betweenbrain

**Comment by AmyStephen** [comment]
Fixed. Thanks Matt!

**Comment by betweenbrain** [comment]
Very cool, thanks!

Best,

Matt Thomas
Founder betweenbrain http://betweenbrain.com/™
Lead Developer Construct Template Development
Frameworkhttp://joomlaengineering.com/
Phone: 203.632.9322
Twitter: @betweenbrain
Github: https://github.com/betweenbrain
