### ISSUE TITLE
PHP Errors and No SQL

### ISSUE THREAD

**Issue by jbrice** [Niambie/jfoobar#19]
I have just installed the Component Creator on Joomla 1.7 on a development system. Two obvious problems:
- Firstly "Fatal error: Class 'JFile' not found ..." - cured by adding "jimport('joomla.filesystem.file');" to the code in create.php.
- Secondly, no SQL code generated nor added to the site database.

**Comment by AmyStephen** [comment]
Very strange - many are installing and creating components (including myself) using JFoobar. 

I am wondering if all the files were copied on install. There is a known issue with Joomla installation and the tar.gz file. Is it possible you used that file for installation? 

Sorry for your trouble!

**Comment by jbrice** [comment]
Hi Amy, 
Many thanks for the quick feedback on this. I had indeed used the .tar.gz version of the extension. I deleted JFoobar, cleaned up, and re-installed from the .zip version from github. 
The result - still getting the PHP error " Fatal error: Class 'JFile' not found in /home/jb/web_test/joomla_17/administrator/components/com_jfoobar/media/create.php on line 118", and once again cured by adding the jimport line mentioned above.
However there's good news - with that additional line of code JFoobar seems now to be working as designed. Do let me know if you want any help in following up this bug.

**Comment by betweenbrain** [comment]
Hi jbrice,

Can you tell us more about the system this occuring with? Php / database
version... Etc. Have you tried reproducing this on another computer? I ask
as I have recently tested jfoobar and didn't experience these issues.

Best,

Matt

Sent from my phone that uses an open source operating system.
On Sep 15, 2011 5:01 AM, "jbrice" <
reply@reply.github.com>
wrote:

**Comment by jbrice** [comment]
Sorry about the delay in getting back to you about this.  Here is the dump of the Joomla Sys. Info. page (it's XAMPP running in Ubuntu 10.04):
PHP Built On     Linux no6-ubuntu 2.6.32-34-generic #77-Ubuntu SMP Tue Sep 13 19:40:53 UTC 2011 i686
Database Version     5.1.30
Database Collation   utf8_general_ci
PHP Version  5.2.8
Web Server   Apache/2.2.11 (Unix) DAV/2 mod_ssl/2.2.11 OpenSSL/0.9.8i PHP/5.2.8 mod_apreq2-20051231/2.6.0 mod_perl/2.0.4 Perl/v5.10.0
WebServer to PHP Interface   apache2handler
Joomla! Version  Joomla! 1.7.1 Stable [ Ember ] 26-Sep-2011 14:00 GMT
Joomla! Platform Version     Joomla Platform 11.2.0 Stable+Modified [ Omar ] 27-Jul-2011 00:00 GMT
User Agent   Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.30 (KHTML, like Gecko) Ubuntu/10.04 Chromium/12.0.742.112 Chrome/12.0.742.112 Safari/534.30

**Comment by radekzm** [comment]
HowTo FIX:

In file /administrator/components/com_jfoobar/media/create.php in line 17 add this:
jimport('joomla.filesystem.file');

I'm looking for thanks :) 
Powered by CMS-Solutions.pl

**Comment by jbrice** [comment]
Err - thanks. But I said that I had applied exactly the same fix that in my earlier posts!
