### ISSUE TITLE
SQL error on unpublish

### ISSUE THREAD

**Issue by stitot** [Niambie/jfoobar#20]
When trying to unpublish an item I get the following error:

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND id=2' at line 3 SQL=UPDATE `joomla_members` SET `state` = 0 WHERE `checked_out` = 0 OR `checked_out` = 42) AND id=2

Unpublishing/publishing categories work fine.

**Comment by mbabker** [comment]
Removed the erroneous closing parentheses, thanks for the report.

**Comment by stitot** [comment]
Better now, but when publishing/unpublishing one item in a category, ALL items gets published/unpublished. And, unpublish have no affect on the site. Unpublished items gets displayed.

**Comment by mbabker** [comment]
I went back and reviewed the parent publish function and the correct fix
was to add an opening parenthesis to the checked out portion of the query
versus removing the closing parenthesis.  It should be good now.

On 9/19/11 4:44 PM, "stitot"
reply@reply.github.com
 wrote:

**Comment by stitot** [comment]
Yes, that fixed the DB update part, but still unpublished items gets displayed on the site.

**Comment by mbabker** [comment]
@AmyStephen, is it intentional to have the default query if the state filter isn't active to pull published and unpublished items?  Seems to me the default should be published only for unauthenticated users and all items if you have front end management capability.

**Comment by mbabker** [comment]
Here's a diff with how I handle the filtering in the front end with my podcast component.  Basically, if you don't have edit or edit state permissions, you only see published items.  I also have a clause that handles the publish_up time so only published articles that aren't set for the future aren't displayed.

https://gist.github.com/1226459
