### ISSUE TITLE
JFoobar Beitrag erstellen/ write Article

### ISSUE THREAD

**Issue by hpb1963** [Niambie/jfoobar#23]
Hi, I am stuck :(

Warning: Invalid argument supplied for foreach() in /libraries/joomla/form/form.php on line 1468

Fatal error: Call to undefined method JUser::getAuthorisedJFoobaregories() in /components/com_kioske/views/form/view.html.php on line 40

Hope you can help me please...

Kind regards

Hans Peter Betzler

**Comment by mbabker** [comment]
Just committed a change to make getAuthorisedJFoobaregories call the
proper getAuthorisedCategories.  Try changing it in your code as well and
see what happens.

On 10/24/11 10:46 PM, "hpb1963"
reply@reply.github.com
 wrote:

**Comment by hpb1963** [comment]
Hi, after this I get:

Warning: Invalid argument supplied for foreach() in /users/hanspeter/www/kostenlosehilfe/libraries/joomla/form/form.php on line 1468

Warning: Invalid argument supplied for foreach() in /users/hanspeter/www/kostenlosehilfe/libraries/joomla/form/form.php on line 1468

Warning: Invalid argument supplied for foreach() in /users/hanspeter/www/kostenlosehilfe/libraries/joomla/form/form.php on line 1468

Warning: Invalid argument supplied for foreach() in /users/hanspeter/www/kostenlosehilfe/libraries/joomla/form/form.php on line 1468

Fatal error: Class 'Categories' not found in /users/hanspeter/www/kostenlosehilfe/components/com_kioske/views/form/view.html.php on line 74

And what should I do now?

Kind regards
Hans Peter Betzler

**Comment by mbabker** [comment]
Fixed the class not found error.  Change Categories to Jcategories and try
again please.

On 10/24/11 11:17 PM, "hpb1963"
reply@reply.github.com
 wrote:

**Comment by hpb1963** [comment]
Hi, thank you, done the change, now I get this :

Warning: Invalid argument supplied for foreach() in /users/hanspeter/www/kostenlosehilfe/libraries/joomla/form/form.php on line 1468

Fatal error: Call to undefined method JUser::getAuthorisedJcategories() in /users/hanspeter/www/kostenlosehilfe/components/com_kioske/views/form/view.html.php on line 41

And what should I do now, please?

Kind regards
Hans Peter Betzler

**Comment by mbabker** [comment]
That line should call JUser::getAuthorisedCategories as we changed with the first commit.  Line 74 of the same file should be changed to JCategories versus Categories.

**Comment by hpb1963** [comment]
OK, thanks you, I have now moved on to EasyCreator.

Maybe you let me know when an update becomes available.

Kind regards
Hans Peter Betzler
