### ISSUE TITLE
HMTL not saving

### ISSUE THREAD

**Issue by esedic** [Niambie/jfoobar#3]
I created a simple example cars/car component.
I added new item (car) and entered text in editor field.
If I format text with HTML and save the item, HTML gets stripped.
I tried different editors (JCE, TinyMCE..) but every time I save the item HTML is not preserved.

**Comment by CristinaSolana** [comment]
Hi Weezle, in your component, click the "Options" button on the top right. In the "Text Filtering" tab, for Super Administrator (and any others you want to be able to use HTML), choose "No Filtering"

**Comment by esedic** [comment]
Thanks Cristina, I was so excited about testing this component that I didn't look at the toolbar at all!

**Comment by CristinaSolana** [comment]
You're welcome.
