### ISSUE TITLE
Source for improvements

### ISSUE THREAD

**Issue by eddieajau** [Niambie/jfoobar#4]
This is more a note than an issue.

I had a similar stab at this kind of thing in 1.5 land but never had the time to update it for 1.6+.  I took the route of build the component with a UI and added a basic templating system for the boiler-plate.  Some of the ideas might be useful to extending your component.  You can find the source here:

http://joomlacode.org/gf/project/theartofjoomla/scmsvn/?action=browse&path=%2Fengineer%2Fcode%2Ftrunk%2Fadministrator%2Fcomponents%2Fcom_engineer%2F

I set it up so you could incrementally add new views and models and things.  Still needed a lot of work though to make it sane.  If it helps, great - if not, that's fine too.

In talking to a lot of developers from around the world there is certainly a niche for this sort of component so it would be great to see other people get behind it.  I do encourage you to run your templates through the Joomla sniff that comes with the platform so that dev's are getting standard compliant code.  I think that would be a good thing to do.

Good job otherwise.

**Comment by CristinaSolana** [comment]
Very cool, Andrew, thanks, I will show Amy and have a look. :) 

Cheers,

Cristina Solana
Frontend Development

Nightshift Creative
Skype: nightshiftc

**Comment by AmyStephen** [comment]
Thanks Andrew - means a lot to have your comments - will look at your code, appreciate that. 

Definitely would like to see developers rally around a component builder, we put it up on the SVN Features Tracker to show our willingness to share it. 

We backported a bit of Molajo code -- but we are doing a lot more, especially with sharing layouts between extension types - and extensions - that I hope you'll find very interesting. Combined with abstracted  code, it starts to get pretty groovy. We can't wait to share that.  This is a very small taste of what we are working on - glad we could share a bit now.

**Comment by eddieajau** [comment]
Having used git for a while now, I wouldn't bother with Subversion anymore. It's a short term gain but long term it's not a sustainable vehicle for collaboration (who would of though I'd ever be saying that).  Github is the place to be now.

**Comment by AmyStephen** [comment]
Sorry for the confusion. The component builder has been uploaded to here (the SVN Feature Tracker): http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26739 as a proposed Feature for Joomla. 

Yes, git is very nice for collaboration although I mainly find it easy because of c. She takes care of me. =)

**Comment by eddieajau** [comment]
Oh, ok.  Why do you see this is something the average site admin would want when they download the Joomla CMS?  Wouldn't you just keep it as a separate developer tool, like JM's translation component?  Then it's not bound to the CMS release cycle so you can respond to changes in the CMS, or developer needs, bugs, etc, more effectively.

**Comment by AmyStephen** [comment]
Best to talk about the contribution here => http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26739

**Comment by eddieajau** [comment]
I can do that.
