### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by K2Joom** [Niambie/jfoobar#7]
Develop an export function to output all required component files, packed as an installer.
Completes the puzzle.

**Comment by ghazal** [comment]
I second that request

**Comment by AmyStephen** [comment]
Simon and ghazal - please download and review the instructions in the Readme.md file Section IV. Create an Installable Component -- it's a pretty straightforward process - please let us know if you have any questions or problems.

**Comment by K2Joom** [comment]
Excellant job Amy!!
Could this be expanded to do this process automatically, as a function within jfoobar?

Example.
In jfoobar, it reads plural names of components created by jfoobar and displays a list.
User can select an extension and click package.
jfoobar then creates a folder of same name in a folder that can be selected by the user (like media folder)
jfoobar then copies the folders from the required location and places them in the selected folder.
Then zips the component up and provides a success notification, with a download link and details of the file path to the zip on the server?

This would save a bit of time and make the process rather slick.
