### ISSUE TITLE
Error in Component Naming 

### ISSUE THREAD

**Issue by K2Joom** [Niambie/jfoobar#9]
Unable to produce components with numerics in the title.

Example:  administrator/index.php?option=com_jfoobar&singular=k2testcomp&plural=k2testcomps

This returns error:   Error loading component: com_k2testcomps, 1
and warning: PLG_SYSTEM_CREATE_INSTALL_SUCCESS (possible missing name in Joomla 1.7 language?)

Component is created, but with numerics ommited from every file and code reference.

**Comment by CristinaSolana** [comment]
I was able to reproduce this error. Fix imminent.
